name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build

    - name: Test Client
      run: cd ihclient/ && go test && cd ..

    - name: Test Converter
      run: cd ihconverter/ && go test && cd ..
