name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platform: [ 'windows', 'linux', 'darwin' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Windows
      if: matrix.platform == 'windows'
      run: CGO_ENABLED=0 GOOS=${{ matrix.platform }} GOARCH=amd64 go build -buildmode=pie -o inspirehep_cli_${{ matrix.platform }}_amd64.exe

    - name: Build Windows
      if: matrix.platform != 'windows'
      run: CGO_ENABLED=0 GOOS=${{ matrix.platform }} GOARCH=amd64 go build -buildmode=pie -o inspirehep_cli_${{ matrix.platform }}_amd64

    - name: Test Client
      run: cd ihclient/ && go test && cd ..

    - name: Test Converter
      run: cd ihconverter/ && go test && cd ..

   
  post_build:
    needs: [build]
    steps:
    - name: Prepare Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          inspirehep_cli_windows_amd64.exe
          inspirehep_cli_linux_amd64
          inspirehep_cli_darwin_amd64
          LICENSE

